### ISSUE TITLE
Typo: guild -> gulid

### ISSUE THREAD

**Issue by ruattd** [simple-robot/simbot-component-qq-guild#104]
### 反馈内容类型

API文档

### 相关链接

[https://simple-robot.github.io/simbot-component-qq-guild/docs/quick-start/stdlib](https://simple-robot.github.io/simbot-component-qq-guild/docs/quick-start/stdlib)

### 内容描述

如题，在 QQ 频道 bot 的 stdlib 文档页的开头依赖声明处有拼写错误，`guild` 被拼写为 `gulid`

~~害得我 gradle sync 了半天也没找到问题在哪~~

对应文件中分别位于 [25 行](https://github.com/simple-robot/simbot-component-qq-guild/blob/1d8a05084485966ea2b8880953ac6e86caf9a2c0/website/docs/quick-start/stdlib.md?plain=1#L25) 和 [34 行](https://github.com/simple-robot/simbot-component-qq-guild/blob/1d8a05084485966ea2b8880953ac6e86caf9a2c0/website/docs/quick-start/stdlib.md?plain=1#L34)

**Comment by ForteScarlet** [comment]
感谢反馈~
